Change QPDF::copyForeignObject to return a null object when called wi…
qpdf/qpdf pull request #1014
Opened 2023-07-25 13:47 UTC by m-holger

…th a /Pages object (fixes #1011)

If copyForeignObject is called with a pages object, the object will not be inserted into the obj_copier.obj_map during normal processing. In the return statement the missing entry is default constructed, with the consequence that an uninitialized object handle is returned. All future references to the object are also replaced with an uninitialized object rather than a null object.

2023-07-25 19:04 UTC, m-holger commented
There probably should be a test case for this.

2023-09-02 19:33 UTC, jberkenbilt commented
Is this made obsolete by #1028?

2023-09-02 19:47 UTC, m-holger commented
No. This one deals with severely damaged files with garbage objects pretending to be page tree nodes

2023-09-02 20:47 UTC, jberkenbilt commented
I agree that there should be a test for this. Do we know how to reproduce it? Anyway, the new code is clearly better than the old code, so I'm inclined to merge it, though I'm worried that taking the change will cover up some other bug. I think I need to understand better when this happens. I think it would be better if we never inserted uninitialized objects rather than detecting them and returning null instead.

2023-09-03 00:18 UTC, m-holger commented
> Do we know how to reproduce it? 

All that is required is to change the /Type entry of a top level foreign object, e.g. the /AcroForm dictionary, to /Pages. 
That will result in the ObjGen not being inserted into obj_copier.object_map. On trying to retrieve the missing object from the object_map it gets default constructed as an uninitialized object handle. Similarly, deliberately trying to foreign copy a /Pages  object will have the same result.

2023-09-03 09:12 UTC, m-holger commented
> Is this made obsolete by https://github.com/qpdf/qpdf/pull/1028?

> No. This one deals with severely damaged files with garbage objects pretending to be page tree nodes

Sorry, it's been a while since I did this. This PR is actually the first commit in #1028

2023-09-03 10:10 UTC, m-holger commented
I've added a test.

>  I think it would be better if we never inserted uninitialized objects rather than detecting them and returning null instead.

I thought it was alright given that the check/fix was at the point of default creation but I've updated to move the check to before the map access.

2023-09-03 12:25 UTC, jberkenbilt requested changes
Great, thanks. Requesting a small change to the warning that I overlooked in my previous review.

2023-09-03 12:25 UTC, jberkenbilt commented on libqpdf/QPDF.cc
>          warn(damagedPDF("Unexpected reference to /Pages object while copying foreign object. "
I missed this before, but to be consistent with the style of most warnings, you could you change this to lower-case and semicolon-separated, as in `unexpected reference to /Pages object while copying foreign object;  replacing with null`

2023-09-03 12:43 UTC, jberkenbilt commented
I'm stepping away for a few hours, but if this is not updated when I return, I will merge as is and tweak the warning message in a separate commit.

2023-09-03 12:47 UTC, jberkenbilt approved these changes

2023-09-03 12:54 UTC, merged