Remove non-standard string_view<unsigned char> from QPDF_Name
qpdf/qpdf pull request #1162
Opened 2024-02-28 20:18 UTC by zclifford

string_view<unsigned char> leads to char_traits<unsigned char> which is not standard C++ (background in https://github.com/qpdf/qpdf/issues/1024).

This triggers compilation failures with certain C++20 compiler configurations.

To avoid this I moved the cast to the loop's range declaration. This should work (for 8-bit characters) despite switching from an explicit cast to an integral conversion, per the following C++17 standards text:

> For each value i of type unsigned char in the range 0 to 255 inclusive, there exists a value j of type char such that the result of an integral conversion from i to char is j, and the result of an integral conversion from j to unsigned char is i.

But if you want me to be more explicit and keep the reinterpret_cast at the cost of an extra line or two I'd be happy to.

https://github.com/qpdf/qpdf/issues/1024

2024-02-28 20:43 UTC, zclifford commented
OK the checks were unhappy (even though the code is fine):

```
/home/runner/work/qpdf/qpdf/libqpdf/QPDF_Name.cc:64:27: error: conversion to ‘unsigned char’ from ‘char’ may change the sign of the result [-Werror=sign-conversion]
   64 |     for (unsigned char c: name) {
      |                           ^~~~
```

Lemme figure out how to edit a pull request :)

2024-02-28 21:29 UTC, zclifford commented
I apparently suck at editing github pull requests

2024-02-29 11:51 UTC, jberkenbilt commented
Just edit/commit with --amend locally and force push. :-) I never edit pull requests in any other way.

2024-02-29 22:06 UTC, zclifford commented
Yeah I deleted the commit and re-created it, which apparently closed the PR so I had to manually reopen it. Will try your suggestion next time.

Git is still a bit foreign to me (what do you mean the rest of the world doesn't use perforce anymore??), especially when tied to a big UI like githubs.

2024-03-01 16:45 UTC, m-holger commented on libqpdf/QPDF_Name.cc
> -    for (auto const& c: view) {
We can simply change c -> ch and  view -> name here and stick with a range based for loop.

2024-03-03 00:07 UTC, jberkenbilt requested changes

2024-03-03 00:07 UTC, jberkenbilt commented on libqpdf/QPDF_Name.cc
> +    for (auto it = name.begin(); it != name.end(); ++it) {
Can't this also be a range for loop? You can change it, or I can merge and then fix. Thanks.

2024-03-03 00:08 UTC, jberkenbilt requested changes
Minor nit -- if you don't get to it, I'll merge and fix. Thanks.

2024-03-03 00:09 UTC, jberkenbilt commented on libqpdf/QPDF_Name.cc
> +    for (auto it = name.begin(); it != name.end(); ++it) {
as in `for (auto const& it: name) {` and just adjust the cast to `it` rather than `*it`.

2024-03-03 18:42 UTC, jberkenbilt commented
I pushed #1167, which includes this change plus my tweak to it. If it passes CI, I will merge it, bringing this along for the ride. Thanks.

2024-03-03 19:06 UTC, merged

2024-03-07 01:53 UTC, zclifford commented
Thanks for getting that for me. I never check work email on weekends as a matter of principle, and I was totally out of commission Monday and Tuesday with a bad cold!

2024-03-07 11:59 UTC, jberkenbilt commented
@zclifford No problem. :-) qpdf isn't work mail for me, so I sometimes ignore it during the week ;-)