Refactor QPDFObject creation and cloning
qpdf/qpdf pull request #717
Opened 2022-06-17 17:35 UTC by m-holger

Move responsibility for creating shared pointers to objects and cloning from QPDFObjectHandle to QPDFObject.

2022-06-18 12:23 UTC, jberkenbilt commented
I think I like this. I need to think through the use of the weak pointer. I'm definitely comfortable with the concept of weak pointers but have never used them in qpdf since, as you know, I was using PointerHolder until the current unreleased changes. The switch to std::shared_ptr makes this possible.

I'd also like to think through the feasibility of changing QPDF_Array and QPDF_Dictionary to hang onto shared_ptr<QPDFObject> instead of QPDFObjectHandle and whether this is a step along the path to doing that. I wonder whether having a parent pointer in QPDFObject as a weak pointer might work as a way to eventually eliminate the shared direct object problem while detecting when it happens. If the situation isn't too bad, I might be up for making it a warning in qpdf 11 and making it a breaking change in qpdf 12.

The method QPDFObjectHandle::releaseResolved breaks circular references by explicitly clearing object pointers in QPDFObjectHandle at destruction. It took a few tries to get that logic right. I know there are tests that fail if that step is missed, though they may only fail when memory sanitizers are in use since they create leaks. I'm pretty sure that code will need to be retained even with weak pointers since it comes about whenever a circular reference exists with actual PDF objects. Object cycles are normal in correct, compliant PDF files. I still would need to think through the interaction of that with this, if any.

2022-06-18 17:06 UTC, m-holger commented
> I'd also like to think through the feasibility of changing QPDF_Array and QPDF_Dictionary to hang onto shared_ptr 

I assume you mean shared_ptr<QPDFObject>. If so, there are a couple of implications
QPDFObject

- qpdf, objid, and generation would need to be moved from QPDFObjectHandle to QPDFObject
- shallowCopy will need to make proper copies of scalar objects
- the way unreserved objects are handled probably would need to change (I haven't checked

2022-06-18 17:09 UTC, m-holger commented
Sorry, accidentally closed

2022-06-25 14:05 UTC, jberkenbilt requested changes
First, I really like this change. There are as few things that need to be different though.

There are two separate things going on, both involving moving things into the QPDFObject classes.

* create -- This is a great change as is.

* clone -- Let's replace `clone()` with `shallowCopy()`. Otherwise, it looks great.

I don't want a method called `clone()` because it is ambiguous as to what kind of copy it is. Perhaps you chose this based on my use of the term `clone` in the coverage cases, but I only used it for types where there is no distinction between a deep and shallow copy.

By the way, my convention is to put the name of the class with the coverage case as the beginning of the second argument to QTC::TC, so all the places where you had `QTC::TC("qpdf", "QPDFObject ...")` should have been `QTC::TC("qpdf", "QPDF_Bool ...")`, etc. It's possible that there may be exceptions to this, and I know there's grep, but it just helps me at a glance when I'm looking at coverage cases.

That said, it has recently come to my attention that `QTC::TC` is slow on Windows if there is a big environment, and while I plan to do some optimization, I'm going to remove coverage cases in performance critical or commonly called sections of code. Some of these were added really early on, and there's just no way the copying code is not covered, so the explicit coverage cases don't add any value. I'm planning on removing a bunch, including those ones, so you may as well just drop the coverage calls.

Thanks for this -- this is a great improvement.

2022-06-25 14:05 UTC, jberkenbilt commented on qpdf/qpdf.testcov
> -QPDFObjectHandle clone bool 0
Just remove these without replacing them.

2022-06-25 14:05 UTC, jberkenbilt commented on qpdf/qpdf.testcov
> -QPDFObjectHandle shallow copy array 0
just remove

2022-06-27 11:05 UTC, m-holger commented on libqpdf/QPDFObject.cc
> +    obj->self = obj;
Removed for now

2022-06-27 11:06 UTC, m-holger commented on libqpdf/QPDF_Array.cc
> +#include <qpdf/QTC.hh>
Done

2022-06-27 11:07 UTC, m-holger commented on libqpdf/QPDF_Bool.cc
> +#include <qpdf/QTC.hh>
Done

2022-06-27 11:07 UTC, m-holger commented on libqpdf/QPDF_Dictionary.cc
> +    QTC::TC("qpdf", "QPDFObject shallow copy dictionary");
Done

2022-06-27 11:08 UTC, m-holger commented on qpdf/qpdf.testcov
> -QPDFObjectHandle clone bool 0
Done

2022-06-27 11:08 UTC, m-holger commented on qpdf/qpdf.testcov
> -QPDFObjectHandle shallow copy array 0
Done

2022-06-27 11:41 UTC, m-holger commented on libqpdf/QPDF_Bool.cc
> +    QTC::TC("qpdf", "QPDFObject clone bool");
Done

2022-06-27 11:41 UTC, m-holger commented on libqpdf/QPDF_Integer.cc
> +#include <qpdf/QTC.hh>
Done

2022-06-27 14:32 UTC, jberkenbilt commented
Great except you called it `shallow_copy` instead of `shallowCopy`. For C++, cameCase is the convention for method names and is used for everything else in QPDFObject and QPDFObjectHandle, so I would prefer `shallowCopy`. Otherwise, I think this is ready to go.

2022-06-27 15:50 UTC, m-holger commented
I plead temporary insanity!

2022-06-27 16:46 UTC, jberkenbilt commented
Thanks for this change! (I'm going to accept `do_create` rather than `doCreate` on the basis of its being a static method.)

2022-06-27 16:47 UTC, merged