Add new convenience class QPDFObjGen::Guard
qpdf/qpdf pull request #929
Opened 2023-03-19 16:37 UTC by m-holger

Support the common pattern of using sets of QPDFObjGen s to detect loops.  

To reduce boiler plate and for a slight performance improvement.

2023-04-01 13:57 UTC, jberkenbilt requested changes
This is fine but I don't understand your choice of names of the local variables. If the set was called `seen`, why is the guard called `unseen`? When I see `unseen.enter(...)`, it makes me feel like it's saying that something is now unseen. I would prefer not to see inversion of the names of the guard variables. Whatever the old set was called, the guard should be called the same thing. In some cases, a name change may be in order. For example, if you only enter and never exit, `visited` is probably fine, but if you enter and exit, `visiting` would probably be better. Maybe you can explain why you chose the names you did, inverting the grammatical sense of my original choices in some but not all cases.

It would also be useful to describe in a comment how guard is intended to be used since it is in the public API.

I'm not sure I like the name `Guard`. To me, a guard is typically something whose existence prevents you from doing something and whose destruction allows it again, kind of like the lock of a mutex. Also, I would prefer `leave` to `exit`. I'd be concerned about `exit` being a macro on some platform. As a rule, I try to avoid using names that are very common and old C library functions. This has gotten me in trouble before. I have had to break API for this before as with strcasecmp.

Would you be comfortable with calling this `Tracker` instead of `Guard`? Or can you suggest a different name?

These comments are all about names. The functionality is fine.

2023-04-01 13:57 UTC, jberkenbilt commented on include/qpdf/QPDFOutlineDocumentHelper.hh
> +        // ABI: remove  QPDF_DLL and pass og by value.
yep, thanks. This should never have been exported.

2023-04-02 11:38 UTC, m-holger commented
I had difficulties thinking of a good name. I think I like `Tracker`.

>  If the set was called seen, why is the guard called unseen? 

I was thinking of a guard as a gatekeeper, in this case a gatekeeper that only allow unseen objects to enter. If we think of it as a tracker, `Tracker seen` makes sense to me.

With tracker, it would feel more natural to me to have `seen.remove(og)` rather than `seen.exit(og)`. 

I am also not sure whether `if (seen.enter(og)) ...` clearly communicates that this is true the first time we encounter `og`. Would `seen.addNew(og)` or `seen.firstTime(og)` be clearer?

2023-04-02 12:52 UTC, jberkenbilt commented
How about just `add` and `remove`?

2023-05-19 17:02 UTC, m-holger commented
I have reworked QPDFObjGen::Guard / Tracker to inherit from std::set<QPDFObjGen> because I found that occasionally I needed additional set methods.

In view that the class now supports all std::set methods I thought that QPDFObjGen::set would be a better name. I kept the method name 'add' since the method is significantly different from the standard insert, but replaced 'remove' with the standard 'erase'.

2023-05-19 18:11 UTC, m-holger commented on libqpdf/QPDF.cc
> +            }
It appears to me that obj_copier.visiting is unnecessary, since the actual loop avoidance can be achieved by checking the object_map.

2023-05-20 18:09 UTC, jberkenbilt approved these changes
I like this solution better.

2023-05-20 18:09 UTC, merged